name: ct312h_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.1.1
  flutter_dotenv: ^5.2.1
  pocketbase: ^0.22.0
  provider: ^6.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/fonts/
    - assets/lotties/
